CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes

BOOTMAGIC_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
SEND_STRING_ENABLE = no
UNICODE_ENABLE = no

AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
ENCODER_ENABLE = no
MIDI_ENABLE = no
OLED_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
